<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>drone_mission</name>
  <version>0.1.0</version>
  <description>Autonomous waypoint mission controller for ArduPilot SITL via MAVROS2</description>
  <maintainer email="ahmad@example.com">Ahmad</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>mavros_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>mavros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
